In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.model_selection import train_test_split
#from sklearn import metrics
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn_extra.cluster import KMedoids

In [2]:
#10x10 grid, monday(4/11) - smsin / friday(8/11)
data = pd.read_csv("../csv/10x10/classif_10x10_smsin.csv")
#data = pd.read_csv("../csv/20x20/classif20x20frid_smsin.csv")

data.head()

Unnamed: 0  cellid    smsin0    smsin1    smsin2    smsin3    smsin4  \
0           0    4379  0.000378  0.000199  0.000000  0.000009  0.000158   
1           1    4380  0.001471  0.000311  0.000028  0.000002  0.000158   
2           2    4381  0.001256  0.000577  0.000052  0.000030  0.000086   
3           3    4382  0.002337  0.001663  0.000779  0.000445  0.000220   
4           4    4383  0.002504  0.001642  0.000703  0.000390  0.000237   

     smsin5    smsin6    smsin7  ...   smsin15   smsin16   smsin17   smsin18  \
0  0.000204  0.000482  0.001992  ...  0.004781  0.005944  0.005330  0.005470   
1  0.000302  0.000998  0.003448  ...  0.008373  0.009585  0.010007  0.008427   
2  0.000308  0.000879  0.003441  ...  0.006474  0.006290  0.006895  0.005045   
3  0.000678  0.002451  0.011564  ...  0.023814  0.023962  0.022650  0.019704   
4  0.000710  0.002671  0.012310  ...  0.022289  0.022932  0.023358  0.020317   

    smsin19   smsin20   smsin21   smsin22   smsin23  hwf  
0  0.003900  0.005816  0.003817  0.004231  0.000898    1  
1  0.007845  0.009887  0.006584  0.007445  0.002440    0  
2  0.004978  0.005282  0.003231  0.002469  0.001343    1  
3  0.017173  0.021170  0.016779  0.012174  0.008751    1  
4  0.018138  0.020992  0.017747  0.012685  0.009127    1  

[5 rows x 27 columns]

In [3]:
y = data.iloc[:,26] #h/w
x = data.iloc[:,2:26] #sms, calls, internet

In [4]:
y

0     1
1     0
2     1
3     1
4     1
     ..
95    1
96    1
97    1
98    1
99    0
Name: hwf, Length: 100, dtype: int64

In [5]:
x

smsin0    smsin1    smsin2    smsin3    smsin4    smsin5    smsin6  \
0   0.000378  0.000199  0.000000  0.000009  0.000158  0.000204  0.000482   
1   0.001471  0.000311  0.000028  0.000002  0.000158  0.000302  0.000998   
2   0.001256  0.000577  0.000052  0.000030  0.000086  0.000308  0.000879   
3   0.002337  0.001663  0.000779  0.000445  0.000220  0.000678  0.002451   
4   0.002504  0.001642  0.000703  0.000390  0.000237  0.000710  0.002671   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.004450  0.001947  0.000219  0.000548  0.000883  0.000611  0.002162   
96  0.003513  0.000866  0.000203  0.001060  0.000802  0.000297  0.001751   
97  0.001513  0.000011  0.000364  0.000026  0.000016  0.001254  0.001070   
98  0.001673  0.000010  0.000567  0.000004  0.000021  0.001169  0.001048   
99  0.001732  0.000010  0.000568  0.000001  0.000045  0.001066  0.001090   

      smsin7    smsin8    smsin9  ...   smsin14   smsin15   smsin16   smsin17  \
0   0.001992  0.004211  0.005459  ...  0.004141  0.004781  0.005944  0.005330   
1   0.003448  0.007770  0.008911  ...  0.009113  0.008373  0.009585  0.010007   
2   0.003441  0.005561  0.008328  ...  0.007181  0.006474  0.006290  0.006895   
3   0.011564  0.017392  0.020199  ...  0.018495  0.023814  0.023962  0.022650   
4   0.012310  0.018621  0.021637  ...  0.017875  0.022289  0.022932  0.023358   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  0.012170  0.030336  0.029843  ...  0.031907  0.034641  0.036360  0.033667   
96  0.009536  0.025224  0.025479  ...  0.025200  0.028675  0.034028  0.029602   
97  0.007833  0.013585  0.012680  ...  0.017322  0.011205  0.013219  0.018971   
98  0.007619  0.013471  0.015583  ...  0.021011  0.012340  0.014052  0.021569   
99  0.007231  0.012148  0.014666  ...  0.018646  0.010969  0.012983  0.019492   

     smsin18   smsin19   smsin20   smsin21   smsin22   smsin23  
0   0.005470  0.003900  0.005816  0.003817  0.004231  0.000898  
1   0.008427  0.007845  0.009887  0.006584  0.007445  0.002440  
2   0.005045  0.004978  0.005282  0.003231  0.002469  0.001343  
3   0.019704  0.017173  0.021170  0.016779  0.012174  0.008751  
4   0.020317  0.018138  0.020992  0.017747  0.012685  0.009127  
..       ...       ...       ...       ...       ...       ...  
95  0.034623  0.041014  0.028946  0.025537  0.025126  0.013038  
96  0.030070  0.036506  0.025207  0.020171  0.021203  0.011985  
97  0.014667  0.015762  0.006884  0.005948  0.006453  0.002682  
98  0.016624  0.017591  0.008534  0.006689  0.006930  0.002680  
99  0.015083  0.016010  0.007589  0.005930  0.005585  0.002466  

[100 rows x 24 columns]

In [6]:
knn = KNeighborsClassifier(n_neighbors=10)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)

In [7]:
#print(scores1.mean(dtype=np.float64))
#print(scores2)
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %f accuracy with a standard deviation of %f" % (scores2.mean(dtype=np.float64), scores2.std(dtype=np.float64)))
print(scores2)

5 fold: 0.37 accuracy with a standard deviation of 0.12
10 fold: 0.350000 accuracy with a standard deviation of 0.120416
[0.2 0.2 0.3 0.2 0.5 0.4 0.5 0.5 0.4 0.3]


In [8]:
#y_predt = cross_val_predict(knn, x, y, cv=5) #10

In [9]:
data = pd.read_csv("../csv/10x10/classif_10x10_smsout.csv")
#data = pd.read_csv("../csv/20x20/classif20x20frid_smsout.csv")

data.head()
#20x20 grid, monday(4/11) - smsout / friday(8/11)

Unnamed: 0  cellid   smsout0   smsout1   smsout2   smsout3   smsout4  \
0           0    4379  0.000506  0.000249  0.000010  0.000002  0.000048   
1           1    4380  0.001622  0.001365  0.010339  0.011154  0.010858   
2           2    4381  0.001115  0.000370  0.000138  0.000000  0.000008   
3           3    4382  0.001870  0.001042  0.001751  0.000000  0.000118   
4           4    4383  0.002081  0.001223  0.001724  0.000019  0.000104   

    smsout5   smsout6   smsout7  ...  smsout15  smsout16  smsout17  smsout18  \
0  0.000005  0.000482  0.001283  ...  0.003694  0.002877  0.002676  0.003814   
1  0.011243  0.008890  0.002497  ...  0.004583  0.005636  0.007947  0.013844   
2  0.000008  0.000418  0.002093  ...  0.003074  0.002176  0.002187  0.003226   
3  0.000118  0.001525  0.011887  ...  0.017044  0.013721  0.014986  0.016102   
4  0.000402  0.001724  0.013061  ...  0.017347  0.015103  0.015889  0.017413   

   smsout19  smsout20  smsout21  smsout22  smsout23  hwf  
0  0.002715  0.003396  0.003801  0.002788  0.001381    1  
1  0.006955  0.005852  0.005189  0.005335  0.002228    0  
2  0.002198  0.003144  0.001724  0.001970  0.001457    1  
3  0.012975  0.016939  0.014571  0.012702  0.009930    1  
4  0.014364  0.017910  0.015497  0.013267  0.010571    1  

[5 rows x 27 columns]

In [10]:
y = data.iloc[:,26] #h/w
x = data.iloc[:,2:26] #sms, calls, internet

In [11]:
knn = KNeighborsClassifier(n_neighbors=10)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)

In [12]:
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %f accuracy with a standard deviation of %f" % (scores2.mean(), scores2.std()))
print(scores2)

5 fold: 0.41 accuracy with a standard deviation of 0.12
10 fold: 0.470000 accuracy with a standard deviation of 0.155242
[0.3 0.2 0.6 0.5 0.5 0.6 0.6 0.7 0.4 0.3]


In [13]:
#y_predt = cross_val_predict(knn, x, y, cv=5) #10

In [14]:
data = pd.read_csv("../csv/10x10/classif_10x10_callin.csv")
#data = pd.read_csv("../csv/20x20/classif20x20frid_callin.csv")

data.head()
#20x20 grid, monday(4/11) - callin / friday(8/11)

Unnamed: 0  cellid   callin0   callin1   callin2  callin3   callin4  \
0           0    4379  0.000204  0.000716  0.000118      0.0  0.000000   
1           1    4380  0.001311  0.000462  0.000277      0.0  0.000101   
2           2    4381  0.000364  0.000249  0.000000      0.0  0.000000   
3           3    4382  0.001501  0.000915  0.000000      0.0  0.000000   
4           4    4383  0.001647  0.000863  0.000014      0.0  0.000035   

    callin5   callin6   callin7  ...  callin15  callin16  callin17  callin18  \
0  0.000324  0.000149  0.002093  ...  0.009150  0.013073  0.010728  0.009591   
1  0.000388  0.000334  0.004638  ...  0.014708  0.017623  0.016723  0.013522   
2  0.000218  0.000499  0.004747  ...  0.010988  0.011554  0.011801  0.008018   
3  0.001501  0.002771  0.010943  ...  0.031121  0.046033  0.046125  0.048560   
4  0.001550  0.002651  0.011641  ...  0.033412  0.046762  0.046555  0.051328   

   callin19  callin20  callin21  callin22  callin23  hwf  
0  0.008018  0.004955  0.003183  0.001443  0.000482    1  
1  0.013662  0.008128  0.004873  0.002610  0.001061    0  
2  0.007783  0.004720  0.002418  0.000904  0.000619    1  
3  0.024682  0.020695  0.009119  0.004223  0.004496    1  
4  0.025946  0.021297  0.010219  0.004508  0.005045    1  

[5 rows x 27 columns]

In [15]:
y = data.iloc[:,26] #h/w
x = data.iloc[:,2:26] #sms, calls, internet

In [16]:
knn = KNeighborsClassifier(n_neighbors=10)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)

In [17]:
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %f accuracy with a standard deviation of %f" % (scores2.mean(dtype=np.float64), scores2.std(dtype=np.float64)))
print(scores2)

5 fold: 0.45 accuracy with a standard deviation of 0.07
10 fold: 0.500000 accuracy with a standard deviation of 0.148324
[0.5 0.4 0.4 0.4 0.5 0.3 0.7 0.6 0.8 0.4]


In [18]:
#y_predt = cross_val_predict(knn, x, y, cv=5) #10

In [19]:
data2 = pd.read_csv("../csv/10x10/classif_10x10_callout.csv")
#data = pd.read_csv("../csv/20x20/classif20x20frid_callout.csv")

data2.head()
#20x20 grid, monday(4/11) - callout / friday(8/11)

Unnamed: 0  cellid  callout0  callout1  callout2  callout3  callout4  \
0           0    4379  0.000010  0.000097  0.000000  0.000000  0.000005   
1           1    4380  0.000157  0.000057  0.000000  0.000009  0.000000   
2           2    4381  0.000294  0.000040  0.000023  0.000017  0.000000   
3           3    4382  0.000525  0.000497  0.000245  0.000252  0.000000   
4           4    4383  0.000594  0.000537  0.000273  0.000308  0.000000   

   callout5  callout6  callout7  ...  callout15  callout16  callout17  \
0  0.000152  0.000584  0.002842  ...   0.009999   0.009711   0.011318   
1  0.000237  0.000978  0.006365  ...   0.017284   0.016388   0.019477   
2  0.000282  0.000605  0.006603  ...   0.010329   0.010004   0.012635   
3  0.000538  0.001771  0.013803  ...   0.034587   0.036961   0.052016   
4  0.000442  0.001830  0.014267  ...   0.036211   0.037631   0.053166   

   callout18  callout19  callout20  callout21  callout22  callout23  hwf  
0   0.008949   0.005031   0.005754   0.002906   0.001478   0.000600    1  
1   0.015358   0.011301   0.008685   0.005553   0.002499   0.000675    0  
2   0.010447   0.005459   0.004089   0.003268   0.001387   0.000201    1  
3   0.038642   0.024501   0.022786   0.009294   0.009220   0.002008    1  
4   0.038921   0.024180   0.022625   0.010503   0.009822   0.002100    1  

[5 rows x 27 columns]

In [20]:
y = data2.iloc[:,26] #h/w
x = data2.iloc[:,2:26] #sms, calls, internet

In [21]:
knn = KNeighborsClassifier(n_neighbors=10)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)

In [22]:
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %f accuracy with a standard deviation of %f" % (scores2.mean(dtype=np.float64), scores2.std(dtype=np.float64)))
print(scores2)

5 fold: 0.54 accuracy with a standard deviation of 0.08
10 fold: 0.540000 accuracy with a standard deviation of 0.111355
[0.5 0.3 0.6 0.6 0.6 0.4 0.7 0.6 0.6 0.5]


In [23]:
y_predt = cross_val_predict(knn, x, y, cv=10) #10

In [24]:
data = pd.read_csv("../csv/10x10/classif_10x10_internet.csv")
#data = pd.read_csv("../csv/20x20/classif20x20frid_internet.csv")

data.head()
#20x20 grid, monday(4/11) - internet / friday(8/11)

Unnamed: 0  cellid  internet0  internet1  internet2  internet3  internet4  \
0           0    4379   0.001156   0.000679   0.000565   0.000423   0.001043   
1           1    4380   0.003133   0.002869   0.002370   0.002010   0.002081   
2           2    4381   0.001304   0.000334   0.000094   0.000046   0.000000   
3           3    4382   0.016952   0.009472   0.007791   0.008543   0.008565   
4           4    4383   0.018275   0.009835   0.008145   0.008830   0.008873   

   internet5  internet6  internet7  ...  internet15  internet16  internet17  \
0   0.000811   0.002498   0.004719  ...    0.005316    0.006002    0.005836   
1   0.002340   0.004176   0.008408  ...    0.009216    0.010459    0.010937   
2   0.000416   0.001071   0.002983  ...    0.003465    0.005087    0.004949   
3   0.009853   0.014072   0.020882  ...    0.021532    0.022824    0.025501   
4   0.010012   0.014286   0.022235  ...    0.023847    0.024706    0.028019   

   internet18  internet19  internet20  internet21  internet22  internet23  hwf  
0    0.006476    0.004789    0.004754    0.003481    0.002299    0.001544    1  
1    0.010560    0.010230    0.009848    0.008094    0.006161    0.004987    0  
2    0.004298    0.004040    0.004338    0.003967    0.002091    0.001535    1  
3    0.026494    0.023700    0.024174    0.024676    0.018218    0.014569    1  
4    0.028422    0.025402    0.026006    0.026480    0.019612    0.015499    1  

[5 rows x 27 columns]

In [25]:
y = data.iloc[:,26] #h/w
x = data.iloc[:,2:26] #sms, calls, internet

In [26]:
knn = KNeighborsClassifier(n_neighbors=10)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)
print(np.std(scores2))

0.15491933384829668


In [27]:
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %f accuracy with a standard deviation of %f" % (scores2.mean(dtype=np.float64), scores2.std(dtype=np.float64)))
print(scores2)

5 fold: 0.39 accuracy with a standard deviation of 0.10
10 fold: 0.400000 accuracy with a standard deviation of 0.154919
[0.1 0.2 0.5 0.3 0.6 0.4 0.6 0.4 0.5 0.4]


In [28]:
#y_predt = cross_val_predict(knn, x, y, cv=5) #10

In [ ]:
predicted = pd.DataFrame(np.transpose(y_predt),columns=['predicted'])
predicted['cellid']=data2.cellid
predicted.head()

predicted  cellid
0          1    4379
1          2    4380
2          1    4381
3          1    4382
4          1    4383

In [35]:
predicted.to_csv('../csv/predicted_co_10x10.csv')